import { jsPDF } from 'jspdf';

interface ReportData {
  title: string;
  subtitle?: string;
  summaryCards: Array<{ label: string; value: string }>;
  tables: Array<{
    title: string;
    headers: string[];
    rows: string[][];
  }>;
  filename: string;
  accentColor?: [number, number, number]; // RGB
}

export function generatePDF(data: ReportData): void {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 20;
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  // Set accent color if provided
  const accentColor = data.accentColor || [37, 99, 235]; // Default blue

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(...accentColor);
  pdf.text(data.title, margin, yPosition);
  yPosition += 12;

  // Subtitle
  if (data.subtitle) {
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text(data.subtitle, margin, yPosition);
    yPosition += 8;
  }

  // Summary Cards
  if (data.summaryCards.length > 0) {
    yPosition += 5;
    pdf.setFontSize(10);
    pdf.setTextColor(...accentColor);
    pdf.text('Summary', margin, yPosition);
    yPosition += 8;

    const cardWidth = (contentWidth - 8) / 3;
    const cardHeight = 25;

    data.summaryCards.forEach((card, index) => {
      const xPos = margin + index * (cardWidth + 4);

      // Card border
      pdf.setDrawColor(...accentColor);
      pdf.rect(xPos, yPosition, cardWidth, cardHeight, 'S');

      // Card content
      pdf.setFontSize(9);
      pdf.setTextColor(100);
      pdf.text(card.label, xPos + 3, yPosition + 6);

      pdf.setFontSize(14);
      pdf.setTextColor(...accentColor);
      pdf.text(card.value, xPos + 3, yPosition + 16);
    });

    yPosition += cardHeight + 12;
  }

  // Tables
  data.tables.forEach((table, tableIndex) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 50) {
      pdf.addPage();
      yPosition = 20;
    }

    // Table title
    pdf.setFontSize(12);
    pdf.setTextColor(...accentColor);
    pdf.text(table.title, margin, yPosition);
    yPosition += 8;

    // Table header
    const cellHeight = 7;
    const colWidth = contentWidth / table.headers.length;

    pdf.setFontSize(9);
    pdf.setTextColor(255);
    pdf.setFillColor(...accentColor);

    table.headers.forEach((header, colIndex) => {
      pdf.rect(
        margin + colIndex * colWidth,
        yPosition,
        colWidth,
        cellHeight,
        'F'
      );
      pdf.text(
        header,
        margin + colIndex * colWidth + 2,
        yPosition + 5,
        { maxWidth: colWidth - 4 }
      );
    });

    yPosition += cellHeight;

    // Table rows
    pdf.setTextColor(0);
    let rowColor = false;

    table.rows.forEach((row, rowIndex) => {
      // Alternate row colors
      if (rowColor) {
        pdf.setFillColor(240, 240, 240);
        pdf.rect(margin, yPosition, contentWidth, cellHeight, 'F');
      }

      row.forEach((cell, colIndex) => {
        pdf.text(
          cell,
          margin + colIndex * colWidth + 2,
          yPosition + 5,
          { maxWidth: colWidth - 4 }
        );
      });

      rowColor = !rowColor;
      yPosition += cellHeight;

      // Check if we need a new page
      if (yPosition > pageHeight - 20) {
        pdf.addPage();
        yPosition = 20;
      }
    });

    yPosition += 5;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(
    `Generated by Finance Tracker on ${new Date().toLocaleDateString('en-IN')}`,
    margin,
    pageHeight - 10
  );

  // Save PDF
  pdf.save(data.filename);
}
