import { jsPDF } from 'jspdf';

interface ReportData {
  title: string;
  subtitle?: string;
  summaryCards: Array<{ label: string; value: string }>;
  tables: Array<{
    title: string;
    headers: string[];
    rows: string[][];
  }>;
  filename: string;
  accentColor?: [number, number, number]; // RGB
}

export function generatePDF(data: ReportData): void {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 12;
    const contentWidth = pageWidth - 2 * margin;
    const accentColor = data.accentColor || [37, 99, 235];
    const footerHeight = 10;
    let yPosition = 8;

    // Helper function to add page if needed
    const checkPageBreak = (requiredSpace: number): void => {
      if (yPosition + requiredSpace > pageHeight - footerHeight - 5) {
        addFooter();
        pdf.addPage();
        yPosition = 15;
      }
    };

    // Helper function to add footer
    const addFooter = (): void => {
      const currentPage = pdf.internal.pages.length - 1;
      pdf.setFontSize(7);
      pdf.setTextColor(150);
      pdf.text(
        `Generated by Finance Tracker • ${new Date().toLocaleDateString('en-IN')}`,
        margin,
        pageHeight - 5
      );
      pdf.setTextColor(150);
      pdf.text(
        `Page ${currentPage}`,
        pageWidth - margin - 15,
        pageHeight - 5
      );
    };

    // Helper function to truncate text smartly
    const truncateText = (text: string, maxLength: number): string => {
      if (text.length <= maxLength) return text;
      return text.substring(0, maxLength - 3) + '...';
    };

    // ===== HEADER =====
    pdf.setFillColor(...accentColor);
    pdf.rect(0, 0, pageWidth, 25, 'F');

    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(255, 255, 255);
    const titleLines = pdf.splitTextToSize(data.title, contentWidth);
    pdf.text(titleLines[0] || data.title, margin, 10);

    if (data.subtitle) {
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(220, 220, 220);
      const subtitleLines = pdf.splitTextToSize(data.subtitle, contentWidth);
      pdf.text(subtitleLines[0] || data.subtitle, margin, 17);
    }

    yPosition = 32;

    // ===== SUMMARY CARDS =====
    if (data.summaryCards && data.summaryCards.length > 0) {
      const cardsPerRow = 2;
      const cardSpacing = 3;
      const cardWidth = (contentWidth - cardSpacing) / cardsPerRow;
      const cardHeight = 18;
      const rowsNeeded = Math.ceil(data.summaryCards.length / cardsPerRow);
      const totalCardHeight = rowsNeeded * (cardHeight + 3) + 12;

      checkPageBreak(totalCardHeight);

      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...accentColor);
      pdf.text('Financial Summary', margin, yPosition);
      yPosition += 6;

      data.summaryCards.forEach((card, index) => {
        const row = Math.floor(index / cardsPerRow);
        const col = index % cardsPerRow;
        const xPos = margin + col * (cardWidth + cardSpacing);
        const yPos = yPosition + row * (cardHeight + 3);

        // Card background
        pdf.setFillColor(245, 247, 250);
        pdf.rect(xPos, yPos, cardWidth, cardHeight, 'F');

        // Card border
        pdf.setDrawColor(...accentColor);
        pdf.setLineWidth(0.6);
        pdf.rect(xPos, yPos, cardWidth, cardHeight, 'S');

        // Card label
        pdf.setFontSize(7);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(100, 100, 100);
        const labelText = truncateText(card.label, 30);
        pdf.text(labelText, xPos + 2, yPos + 4);

        // Card value
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(...accentColor);
        const valueText = truncateText(card.value, 25);
        pdf.text(valueText, xPos + 2, yPos + 13);
      });

      yPosition += rowsNeeded * (cardHeight + 3) + 5;
    }

    // ===== TABLES =====
    if (data.tables && data.tables.length > 0) {
      data.tables.forEach((table) => {
        if (!table.headers || table.headers.length === 0) return;

        checkPageBreak(20);

        // Table title
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(...accentColor);
        pdf.text(table.title || 'Table', margin, yPosition);
        yPosition += 5;

        const headerHeight = 6;
        const rowHeight = 5;
        const numCols = table.headers.length;
        const colWidth = contentWidth / numCols;

        // ===== TABLE HEADER =====
        checkPageBreak(headerHeight + 5);

        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(255, 255, 255);
        pdf.setFillColor(...accentColor);
        pdf.setDrawColor(...accentColor);
        pdf.setLineWidth(0.4);

        table.headers.forEach((header, colIndex) => {
          const xPos = margin + colIndex * colWidth;

          // Header cell background
          pdf.rect(xPos, yPosition, colWidth, headerHeight, 'F');

          // Header text
          pdf.setTextColor(255, 255, 255);
          const maxChars = Math.floor(colWidth / 1.5);
          const truncatedHeader = truncateText(header, maxChars);
          pdf.text(truncatedHeader, xPos + 1, yPosition + 4, {
            maxWidth: colWidth - 2,
          });

          // Header border
          pdf.rect(xPos, yPosition, colWidth, headerHeight, 'S');
        });

        yPosition += headerHeight;

        // ===== TABLE ROWS =====
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(40, 40, 40);
        pdf.setDrawColor(200, 200, 200);
        pdf.setLineWidth(0.2);

        if (table.rows && table.rows.length > 0) {
          table.rows.forEach((row, rowIndex) => {
            checkPageBreak(rowHeight + 2);

            // Ensure row has correct number of cells
            const normalizedRow = Array(numCols).fill('');
            row.forEach((cell, idx) => {
              if (idx < numCols) {
                normalizedRow[idx] = cell || '';
              }
            });

            // Alternate row background
            if (rowIndex % 2 === 1) {
              pdf.setFillColor(245, 247, 250);
              pdf.rect(margin, yPosition, contentWidth, rowHeight, 'F');
            }

            // Row cells
            normalizedRow.forEach((cell, colIndex) => {
              const xPos = margin + colIndex * colWidth;

              // Cell text
              pdf.setFontSize(7.5);
              const maxChars = Math.floor(colWidth / 1.2);
              const truncatedCell = truncateText(String(cell), maxChars);
              pdf.text(truncatedCell, xPos + 1, yPosition + 3.5, {
                maxWidth: colWidth - 2,
              });

              // Cell border
              pdf.rect(xPos, yPosition, colWidth, rowHeight, 'S');
            });

            yPosition += rowHeight;
          });
        }

        yPosition += 3;
      });
    }

    // ===== ADD FOOTER TO LAST PAGE =====
    addFooter();

    // Save PDF
    const filename = data.filename || 'report.pdf';
    const sanitizedFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
    pdf.save(sanitizedFilename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// Generate a printable HTML version for printing
export function generatePrintReport(data: ReportData): void {
  try {
    const accentColorHex = data.accentColor 
      ? `rgb(${data.accentColor[0]}, ${data.accentColor[1]}, ${data.accentColor[2]})`
      : '#2563eb';

    const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${escapeHtml(data.title)}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          background: #f5f5f5;
          padding: 20px;
        }
        
        .container {
          max-width: 900px;
          margin: 0 auto;
          background: white;
          box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
        
        .header {
          background: linear-gradient(135deg, ${accentColorHex} 0%, ${accentColorHex}dd 100%);
          color: white;
          padding: 40px;
          text-align: left;
        }
        
        .header h1 {
          font-size: 32px;
          margin-bottom: 10px;
          font-weight: 700;
          word-wrap: break-word;
        }
        
        .header p {
          font-size: 14px;
          opacity: 0.9;
          word-wrap: break-word;
        }
        
        .content {
          padding: 40px;
        }
        
        .section {
          margin-bottom: 40px;
          page-break-inside: avoid;
        }
        
        .section-title {
          font-size: 18px;
          font-weight: 700;
          color: ${accentColorHex};
          margin-bottom: 20px;
          padding-bottom: 10px;
          border-bottom: 3px solid ${accentColorHex};
        }
        
        .cards {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 15px;
          margin-bottom: 30px;
        }
        
        .card {
          border: 2px solid ${accentColorHex};
          border-radius: 8px;
          padding: 20px;
          background: #f5f7fa;
          text-align: center;
          page-break-inside: avoid;
        }
        
        .card-label {
          font-size: 13px;
          color: #666;
          margin-bottom: 10px;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          word-wrap: break-word;
        }
        
        .card-value {
          font-size: 24px;
          font-weight: 700;
          color: ${accentColorHex};
          word-wrap: break-word;
        }
        
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
          page-break-inside: auto;
        }
        
        thead {
          background: ${accentColorHex};
          color: white;
        }
        
        th {
          padding: 12px;
          text-align: left;
          font-weight: 600;
          font-size: 13px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          word-wrap: break-word;
        }
        
        td {
          padding: 12px;
          border-bottom: 1px solid #e0e0e0;
          word-wrap: break-word;
        }
        
        tbody tr {
          page-break-inside: avoid;
          page-break-after: auto;
        }
        
        tbody tr:nth-child(odd) {
          background: #f5f7fa;
        }
        
        tbody tr:hover {
          background: #eff2f7;
        }
        
        .footer {
          border-top: 1px solid #e0e0e0;
          padding-top: 20px;
          margin-top: 30px;
          text-align: center;
          font-size: 12px;
          color: #999;
        }
        
        @media print {
          body {
            background: white;
            padding: 0;
          }
          
          .container {
            box-shadow: none;
            max-width: 100%;
          }
          
          .no-print {
            display: none;
          }
          
          @page {
            margin: 1cm;
            size: A4;
          }
          
          .section {
            page-break-inside: avoid;
          }
          
          tbody tr:hover {
            background: inherit;
          }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>${escapeHtml(data.title)}</h1>
          ${data.subtitle ? `<p>${escapeHtml(data.subtitle)}</p>` : ''}
        </div>
        
        <div class="content">
          ${
            data.summaryCards && data.summaryCards.length > 0
              ? `
            <div class="section">
              <div class="section-title">Financial Summary</div>
              <div class="cards">
                ${data.summaryCards
                  .map(
                    (card) => `
                  <div class="card">
                    <div class="card-label">${escapeHtml(card.label)}</div>
                    <div class="card-value">${escapeHtml(card.value)}</div>
                  </div>
                `
                  )
                  .join('')}
              </div>
            </div>
          `
              : ''
          }
          
          ${data.tables && data.tables.length > 0
            ? data.tables
                .map(
                  (table) => `
            <div class="section">
              <div class="section-title">${escapeHtml(table.title || 'Table')}</div>
              <table>
                <thead>
                  <tr>
                    ${table.headers
                      .map((header) => `<th>${escapeHtml(header)}</th>`)
                      .join('')}
                  </tr>
                </thead>
                <tbody>
                  ${table.rows && table.rows.length > 0
                    ? table.rows
                        .map(
                          (row) => `
                    <tr>
                      ${row.map((cell) => `<td>${escapeHtml(String(cell || ''))}</td>`).join('')}
                    </tr>
                  `
                        )
                        .join('')
                    : '<tr><td colspan="' + table.headers.length + '" style="text-align: center; color: #999;">No data available</td></tr>'}
                </tbody>
              </table>
            </div>
          `
                )
                .join('')
            : ''}
          
          <div class="footer">
            Generated by Finance Tracker • ${new Date().toLocaleDateString(
              'en-IN'
            )} at ${new Date().toLocaleTimeString('en-IN')}
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

    const printWindow = window.open('', '_blank', 'height=600,width=800');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      
      // Wait for content to load before printing
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          // Don't auto-close - let user decide
        }, 500);
      };
    } else {
      throw new Error('Failed to open print window. Please check if popups are blocked.');
    }
  } catch (error) {
    console.error('Error generating print report:', error);
    throw new Error(`Failed to generate print report: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// Helper function to escape HTML
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}